# meta file for megacli
---
galaxy_info:
  author: Guillaume Gambs
  company: Digimind
  description: Install LSI MegaRAID Linux MegaCLI
  license: MIT
  min_ansible_version: 2.5.0.0
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - system
    - monitoring
dependencies: []
