---
- name: copy resolv.conf
  copy:
    backup: yes
    dest: /etc/resolv.conf
    follow: no
    mode: 0644
    owner: root
    group: root
    remote_src: no
    src: "resolv.conf.{{ hostvars[inventory_hostname].domain }}"
