---
- hosts: all
  gather_facts: True
  roles:
    - ssh-keys
    - role: common
      server_env: dev
    - vrack
    - routes
    - dns
    - iptables
    - role: jdk
      java_packages: jdk-8u131-linux-x64.rpm
    - prometheus-node-exporter
    - sensu-client
