---
- name: Run timedatectl status
  command: /usr/bin/timedatectl status
  changed_when: False
  check_mode: no
  register: timedatectl_result

- name: Set timezone
  command: /usr/bin/timedatectl set-timezone Europe/Paris
  when: "'Europe/Paris' not in timedatectl_result.stdout"
  become: yes

- name: Enable ntp
  command: /usr/bin/timedatectl set-ntp true
  when: "'NTP enabled: no' in timedatectl_result.stdout"
  become: yes

