---
# tasks file for enalean.fusioninventory-agent
#

- name: Install fusioninventory-agent for Debian-like distros
  apt: name="{{fusioninventory_deb_pkg}}" state=present
  when: ansible_os_family == 'Debian'
  notify: FusionInventory agent first execution

- name: Install EPEL repository for RHEL-like distros
  yum: name=epel-release state=present
  when: ansible_os_family == 'RedHat'

- name: Install fusioninventory-agent for RHEL-like distros
  yum: name="{{fusioninventory_rhel_pkg}}" state=present
  when: ansible_os_family == 'RedHat'

- name: Deploy agent configuration
  template: src="agent.cfg.{{ansible_os_family}}.j2" dest="{{fusioninventory_conf_dir}}/agent.cfg" owner=root group=root mode=0644

- name: Install GLPI certificate
  copy: src="certificates/wildcard.master.infra.crt" dest="{{ fusioninventory_cert }}" owner=root group=root mode=0644

- name: Make sure a service fusioninventory-agent.service is running
  systemd: state=started enabled=yes name=fusioninventory-agent.service
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  notify: FusionInventory agent first execution

- name: Make sure a service fusioninventory-agent is running
  service: state=started enabled=yes name=fusioninventory-agent
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  notify: FusionInventory agent first execution

