---
- name: install rpcbind
  yum:
    name: rpcbind
    state: present

- name: enable and start nfs server services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - nfs-server
    - rpcbind
    - nfs-lock
    - nfs-idmap
