---
fusioninventory: []
# defaults file for fusioninventory-agent
#

# The server which we send informations
fusioninventory_server: "https://glpi.master.infra/plugins/fusioninventory/"

# A path for an ssl cert file
fusioninventory_cert: "/etc/fusioninventory/wildcard.master.infra.crt"

# Package to install
fusioninventory_deb_pkg: "fusioninventory-agent"
fusioninventory_rhel_pkg: "fusioninventory-agent"

# Where to install agent configuration
fusioninventory_conf_dir: "/etc/fusioninventory"
